In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv('./All-App-GPU.csv')
data = data[['AppName','compute_version','gpu_id','gpu_name','input_size','max_clock_rate','num_of_cores','L2','bus','memory_clock','bandwith','GM','num_sm','num_cores_sm','theoretical_flops','AppId','duration','grid_x','grid_y','block_x','block_y']]
#data['block_x'].unique()

C:\Users\Luan Siqueira\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py:3441: DtypeWarning: Columns (37) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


array([   8,   16,   32,   64,  256, 1024,  128], dtype=int64)

In [3]:
data['bandwith'].unique()

array([192.256, 288.384, 208.   , 336.48 , 224.32 ])

In [2]:
dados = pd.read_csv('./all-app-gpu-24-09.csv')
dados = dados.drop(columns= ["Unnamed: 0"], axis = 1)
dados

AppName  compute_version  gpu_id gpu_name  \
0     matMul_gpu_uncoalesced              3.0       1  GTX-680   
1     matMul_gpu_uncoalesced              3.0       1  GTX-680   
2     matMul_gpu_uncoalesced              3.0       1  GTX-680   
3     matMul_gpu_uncoalesced              3.0       1  GTX-680   
4     matMul_gpu_uncoalesced              3.0       1  GTX-680   
...                      ...              ...     ...      ...   
8454               subSeqMax              5.2       8  GTX-980   
8455               subSeqMax              5.2       8  GTX-980   
8456               subSeqMax              5.2       8  GTX-980   
8457               subSeqMax              5.2       8  GTX-980   
8458               subSeqMax              5.2       8  GTX-980   

      max_clock_rate  num_of_cores   L2  bus  memory_clock bandwith  GM  \
0               1058          1536  0.5  256          3004   192256   2   
1               1058          1536  0.5  256          3004   192256   2   
2               1058          1536  0.5  256          3004   192256   2   
3               1058          1536  0.5  256          3004   192256   2   
4               1058          1536  0.5  256          3004   192256   2   
...              ...           ...  ...  ...           ...      ...  ..   
8454            1216          2048  2.0  256          3505   224,32   4   
8455            1216          2048  2.0  256          3505   224,32   4   
8456            1216          2048  2.0  256          3505   224,32   4   
8457            1216          2048  2.0  256          3505   224,32   4   
8458            1216          2048  2.0  256          3505   224,32   4   

      num_sm  num_cores_sm  theoretical_flops  AppId      duration  grid_x  \
0          8           192          3250176.0      1  0.0012420700      32   
1          8           192          3250176.0      1  0.0100340000      64   
2          8           192          3250176.0      1  0.0335980000      96   
3          8           192          3250176.0      1  0.0795990000     128   
4          8           192          3250176.0      1  0.1547150000     160   
...      ...           ...                ...    ...           ...     ...   
8454      16           128          4980736.0      9  0.0361190000      32   
8455      16           128          4980736.0      9  0.0367930000      32   
8456      16           128          4980736.0      9  0.0373610000      32   
8457      16           128          4980736.0      9  0.0381840000      32   
8458      16           128          4980736.0      9  0.0388880000      32   

      grid_y  block_x  block_y  
0         32        8        8  
1         64        8        8  
2         96        8        8  
3        128        8        8  
4        160        8        8  
...      ...      ...      ...  
8454       1      128        1  
8455       1      128        1  
8456       1      128        1  
8457       1      128        1  
8458       1      128        1  

[8459 rows x 20 columns]

In [8]:
df = pd.read_csv('./cuda_to_csv/new_test.csv', sep=',', names=['null','AppName','block_x','compute_version','registers','smem','cmem', 'number_of_lines_kernel','occupancy'])
df = df.drop(columns= ["null"], axis = 1)
df['compute_version'].unique()


array([3. , 3.5, 5.2])

In [9]:
data['compute_version'].unique()

array([3. , 3.5, 5.2])

In [10]:
new_dataset = pd.merge(data, df, how = 'outer', on = ['AppName','compute_version','block_x'])
new_dataset.to_csv('Teste-30-09.csv')
#new_dataset[(new_dataset['AppName'] == 'dotProd') & (new_dataset['compute_version'] == 5.2) & (new_dataset['block_x'] == 1024)]